version: '3.8'

volumes:
  static_volume:
  media_volume:

services:
  backend:
    build: backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/

  nginx:
    build: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - backend
