# Generated by Django 4.2.7 on 2023-11-06 06:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='homes',
            fields=[
                ('complex', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Название ЖК')),
                ('link', models.CharField(max_length=255, verbose_name='ссылка ')),
                ('description', models.CharField(max_length=255, verbose_name='описание')),
                ('metro', models.CharField(max_length=255, verbose_name='метро')),
                ('photo', models.CharField(max_length=255, verbose_name='фото')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'дома ',
                'verbose_name_plural': 'дома',
            },
        ),
        migrations.CreateModel(
            name='personal_data1',
            fields=[
                ('passport_series', models.CharField(max_length=255, verbose_name='серия паспорта')),
                ('passport_number', models.CharField(max_length=255, verbose_name='номер паспорта')),
                ('habitation', models.CharField(max_length=255, verbose_name='проживание в данный  момент')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя ')),
                ('last_name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Фамилия')),
                ('registration', models.CharField(max_length=255, verbose_name='регистрация')),
                ('genders', models.CharField(choices=[('a', 'Мужчина'), ('b', 'Женщина'), ('c', 'Трансформер ')], max_length=1, verbose_name='Пол')),
                ('idd', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='логин')),
            ],
            options={
                'verbose_name': 'основные данные  людей ',
                'verbose_name_plural': 'основные данные  людей ',
            },
        ),
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('В', 'в браке'), ('П', 'есть отношения'), ('Х', 'Холост')], max_length=1, verbose_name='Cемейное положение. ')),
                ('children', models.CharField(choices=[('В', 'Взрослые'), ('П', 'Подростки'), ('Р', 'Ребенок'), ('Н', 'Отсутствуют')], max_length=1, verbose_name='Есть ли дети ')),
                ('salary', models.IntegerField(verbose_name='ваша средняя зарплата')),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.personal_data1', verbose_name='ФИО')),
            ],
            options={
                'verbose_name_plural': 'Дополнительная информация людей ',
            },
        ),
        migrations.CreateModel(
            name='housing_cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='тип квартиры_1')),
                ('title1', models.CharField(max_length=255, verbose_name='тип квартиры_2')),
                ('title2', models.CharField(max_length=255, verbose_name='тип квартиры_3')),
                ('title3', models.CharField(max_length=255, verbose_name='тип квартиры_4')),
                ('title4', models.CharField(max_length=255, verbose_name='тип квартиры_5')),
                ('area', models.CharField(max_length=255, verbose_name='площадь')),
                ('area1', models.CharField(max_length=255, verbose_name='площадь')),
                ('area2', models.CharField(max_length=255, verbose_name='площадь')),
                ('area3', models.CharField(max_length=255, verbose_name='площадь')),
                ('area4', models.CharField(max_length=255, verbose_name='площадь')),
                ('prices', models.CharField(max_length=255, verbose_name='цена')),
                ('prices1', models.CharField(max_length=255, verbose_name='цена')),
                ('prices2', models.CharField(max_length=255, verbose_name='цена')),
                ('prices3', models.CharField(max_length=255, verbose_name='цена')),
                ('prices4', models.CharField(max_length=255, verbose_name='цена')),
                ('complex', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.homes', verbose_name='Название дома')),
            ],
            options={
                'verbose_name_plural': 'Стоимость домов ',
            },
        ),
        migrations.CreateModel(
            name='estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_complex', models.CharField(max_length=255, verbose_name='Дом ')),
                ('price', models.CharField(max_length=255, verbose_name='стоимость')),
                ('login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.personal_data1', verbose_name='ФИО')),
            ],
            options={
                'verbose_name_plural': 'купленные квартиры ',
            },
        ),
        migrations.CreateModel(
            name='credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan', models.FloatField(verbose_name='Сумма кредита ')),
                ('term', models.FloatField(verbose_name='время ')),
                ('type_loan', models.CharField(choices=[('О', 'Кредит'), ('И', 'Ипотека')], default='О', max_length=1, verbose_name='Тип кредита ')),
                ('percent', models.IntegerField(verbose_name='Проценты ')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.personal_data1', verbose_name='Логин')),
            ],
            options={
                'verbose_name_plural': 'Кредиты',
            },
        ),
        migrations.CreateModel(
            name='card',
            fields=[
                ('card_number', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='номер карты')),
                ('term', models.CharField(max_length=15, verbose_name='срок действия ')),
                ('balance', models.PositiveBigIntegerField(default=0)),
                ('Cvv', models.CharField(max_length=3)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.personal_data1', verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'картa',
                'verbose_name_plural': 'карты',
            },
        ),
    ]
